# Generated by Django 5.2.5 on 2025-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customerid', models.CharField()),
                ('customername', models.CharField()),
                ('Gender', models.CharField()),
                ('DateOfBirth', models.DateField()),
                ('Phonenumber', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('State', models.CharField()),
                ('City', models.CharField()),
            ],
        ),
    ]
