# Generated by Django 5.2.5 on 2025-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='Customerid',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
