# Generated by Django 5.2.5 on 2025-10-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0002_remove_register_id_alter_register_customerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='customername',
            new_name='Customername',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Customerid',
        ),
        migrations.AddField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
