# Generated by Django 5.2.5 on 2025-10-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0003_rename_customername_register_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
