# Generated by Django 5.2.5 on 2025-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0004_alter_register_phonenumber_alter_register_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='operator',
            fields=[
                ('OID', models.CharField(primary_key=True, serialize=False)),
                ('OName', models.CharField()),
                ('OUsername', models.CharField()),
                ('Password', models.CharField()),
                ('Gender', models.CharField()),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
