# Generated by Django 5.2.5 on 2025-10-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0005_operator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='operator',
            new_name='operat',
        ),
    ]
