# Generated by Django 5.2.5 on 2025-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0006_rename_operator_operat'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicin',
            fields=[
                ('MedicineID', models.IntegerField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField()),
                ('EXPDate', models.DateField()),
                ('ProductCost', models.IntegerField()),
                ('SeellingCost', models.IntegerField()),
                ('Availability', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
