# Generated by Django 5.2.5 on 2025-10-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0007_medicin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicin',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
