# Generated by Django 5.2.5 on 2025-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0008_alter_medicin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Cusid', models.CharField()),
                ('MID', models.IntegerField()),
                ('OperatorID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('BillAmount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='operat',
            name='OID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
