# Generated by Django 5.2.5 on 2025-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0009_transaction_alter_operat_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operat',
            name='OID',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
