# Generated by Django 5.2.5 on 2025-10-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrust', '0010_alter_operat_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operat',
            name='OID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.CharField(),
        ),
    ]
